package pokemon.runtime.data;

import com.badlogic.gdx.utils.JsonValue;

/**
 * R6.27: {@code Data/Animations.rxdata} as generated by the Builder
 * ({@code generated/animations.json}), used by Show Animation (207).
 *
 * <p>Cells live in the RMXP animation canvas (640x320) and point at one cell
 * of the animation's sheet ({@code Graphics/Animations/<graphic>.png}). The
 * runtime uses five logical columns, even when the image's unused rightmost
 * columns have been cropped (see the source project's 0005.rb).</p>
 */
public final class AnimationData {

    public static final class Cell {
        public int cell;
        public int x;
        public int y;
        public int zoom = 100;
        public int angle;
        public boolean flip;
        public int opacity = 255;
        public int blend;
    }

    /** One animation timing: an SE and/or a flash at a given animation frame. */
    public static final class Timing {
        public int frame;
        /** 0 none, 1 hit, 2 miss (map animations are always played as hits). */
        public int condition;
        /** 0 none, 1 target, 2 screen. */
        public int scope;
        public int flashDuration;
        public float red = 255f;
        public float green = 255f;
        public float blue = 255f;
        public float alpha = 255f;
        public String seName;
        public int seVolume = 100;
        public int sePitch = 100;
    }

    public static final class Animation {
        public int id;
        public String name = "";
        public String graphic = "";
        public int hue;
        /** 0 up, 1 middle, 2 down, 3 screen. */
        public int position;
        public int frameMax;
        public Cell[][] frames = new Cell[0][];
        public Timing[] timings = new Timing[0];
    }

    private final Animation[] byId;

    private AnimationData(Animation[] byId) {
        this.byId = byId;
    }

    public static AnimationData parse(JsonValue root) {
        if (root == null) {
            return new AnimationData(new Animation[0]);
        }
        JsonValue list = root.get("animations");
        int maxId = 0;
        if (list != null && list.isArray()) {
            for (JsonValue entry = list.child; entry != null; entry = entry.next) {
                maxId = Math.max(maxId, entry.getInt("id", 0));
            }
        }
        Animation[] byId = new Animation[maxId + 1];
        if (list != null && list.isArray()) {
            for (JsonValue entry = list.child; entry != null; entry = entry.next) {
                Animation animation = parseAnimation(entry);
                if (animation.id >= 0 && animation.id < byId.length) {
                    byId[animation.id] = animation;
                }
            }
        }
        return new AnimationData(byId);
    }

    private static Animation parseAnimation(JsonValue entry) {
        Animation animation = new Animation();
        animation.id = entry.getInt("id", -1);
        animation.name = entry.getString("name", "");
        animation.graphic = entry.getString("graphic", "");
        animation.hue = entry.getInt("hue", 0);
        animation.position = entry.getInt("position", 0);
        animation.frameMax = Math.max(0, entry.getInt("frameMax", 0));
        JsonValue frames = entry.get("frames");
        if (frames != null && frames.isArray()) {
            int count = Math.min(animation.frameMax, frames.size);
            animation.frames = new Cell[count][];
            int frameIndex = 0;
            for (JsonValue frame = frames.child; frame != null && frameIndex < count;
                 frame = frame.next, frameIndex++) {
                if (!frame.isArray()) {
                    animation.frames[frameIndex] = new Cell[0];
                    continue;
                }
                Cell[] cells = new Cell[frame.size];
                int cellIndex = 0;
                for (JsonValue cell = frame.child; cell != null; cell = cell.next, cellIndex++) {
                    Cell parsed = new Cell();
                    parsed.cell = cell.getInt("cell", -1);
                    parsed.x = cell.getInt("x", 0);
                    parsed.y = cell.getInt("y", 0);
                    parsed.zoom = cell.getInt("zoom", 100);
                    parsed.angle = cell.getInt("angle", 0);
                    parsed.flip = cell.getBoolean("flip", false);
                    parsed.opacity = cell.getInt("opacity", 255);
                    parsed.blend = cell.getInt("blend", 0);
                    cells[cellIndex] = parsed;
                }
                animation.frames[frameIndex] = cells;
            }
        }
        JsonValue timings = entry.get("timings");
        if (timings != null && timings.isArray()) {
            animation.timings = new Timing[timings.size];
            int index = 0;
            for (JsonValue timing = timings.child; timing != null; timing = timing.next) {
                Timing parsed = new Timing();
                parsed.frame = timing.getInt("frame", 0);
                parsed.condition = timing.getInt("condition", 0);
                parsed.scope = timing.getInt("scope", 0);
                parsed.flashDuration = timing.getInt("flashDuration", 0);
                JsonValue color = timing.get("color");
                if (color != null && color.isArray() && color.size >= 4) {
                    parsed.red = color.get(0).asFloat();
                    parsed.green = color.get(1).asFloat();
                    parsed.blue = color.get(2).asFloat();
                    parsed.alpha = color.get(3).asFloat();
                }
                JsonValue se = timing.get("se");
                if (se != null && se.isObject()) {
                    parsed.seName = se.getString("name", null);
                    parsed.seVolume = se.getInt("volume", 100);
                    parsed.sePitch = se.getInt("pitch", 100);
                }
                animation.timings[index++] = parsed;
            }
        }
        return animation;
    }

    public Animation animation(int id) {
        if (id <= 0 || id >= byId.length) {
            return null;
        }
        return byId[id];
    }

    public int size() {
        int count = 0;
        for (Animation animation : byId) {
            if (animation != null) {
                count++;
            }
        }
        return count;
    }
}
