module PBEvolution
  
  def self.getName(method)
    method = (method.is_a?(Numeric)) ? method : getConst(PBEvolution, method)
    names = []
    names[None]              = _INTL("无")
    names[Level]             = _INTL("等级达到")
    names[LevelMale]         = _INTL("雄性等级达到")
    names[LevelFemale]       = _INTL("雌性等级达到")
    names[LevelDay]          = _INTL("白天,等级达到")
    names[LevelNight]        = _INTL("黑夜,等级达到")
    names[LevelMorning]      = _INTL("早上,等级达到")
    names[LevelAfternoon]    = _INTL("下午,等级达到")
    names[LevelEvening]      = _INTL("晚上,等级达到")
    names[LevelNoWeather]    = _INTL("无天气,等级达到")
    names[LevelSun]          = _INTL("晴天,等级达到")
    names[LevelRain]         = _INTL("雨天,等级达到")
    names[LevelSnow]         = _INTL("雪天,等级达到")
    names[LevelSandstorm]    = _INTL("沙暴,等级达到")
    names[LevelCycling]      = _INTL("骑车,等级达到")
    names[LevelSurfing]      = _INTL("冲浪,等级达到")
    names[LevelDiving]       = _INTL("潜水,等级达到")
    names[LevelDarkness]     = _INTL("黑暗中等级达到")
    names[LevelDarkInParty]  = _INTL("队伍中有恶属性,等级达到")
    names[AttackGreater]     = _INTL("攻击高于防御")
    names[AtkDefEqual]       = _INTL("攻击防御相等")
    names[DefenseGreater]    = _INTL("防御高于攻击")
    names[Silcoon]           = _INTL("内部数据满足条件1")
    names[Cascoon]           = _INTL("内部数据满足条件2")
    names[Ninjask]           = _INTL("等级达到")        # 铁面忍者
    names[Shedinja]          = _INTL("队伍有空位,背包有精灵球")
    names[Happiness]         = _INTL("亲密度达标")
    names[HappinessMale]     = _INTL("雄性亲密度达标")
    names[HappinessFemale]   = _INTL("雌性亲密度达标")
    names[HappinessDay]      = _INTL("白天,亲密度达标")
    names[HappinessNight]    = _INTL("黑夜,亲密度达标")
    names[HappinessMove]     = _INTL("亲密度达标,学会")
    names[HappinessMoveType] = _INTL("亲密度达标,学会招式包含")
    names[HappinessHoldItem] = _INTL("亲密度达标,携带")
    names[MaxHappiness]      = _INTL("满亲密度")
    names[Beauty]            = _INTL("美丽度达到")
    names[HoldItem]          = _INTL("携带")
    names[HoldItemMale]      = _INTL("雄性携带")
    names[HoldItemFemale]    = _INTL("雌性携带")
    names[DayHoldItem]       = _INTL("白天,携带")
    names[NightHoldItem]     = _INTL("黑夜,携带")
    names[HoldItemHappiness] = _INTL("亲密度达标,携带")
    names[HasMove]           = _INTL("学会招式")
    names[HasMoveType]       = _INTL("学会招式属性")
    names[HasInParty]        = _INTL("队伍中有宝可梦")
    names[Location]          = _INTL("当前位于")    # 地图
    names[Region]            = _INTL("当前位于")    # 地区
    names[Item]              = _INTL("使用")
    names[ItemMale]          = _INTL("雄性使用")
    names[ItemFemale]        = _INTL("雌性使用")
    names[ItemDay]           = _INTL("白天,使用")
    names[ItemNight]         = _INTL("黑夜,使用")
    names[ItemHappiness]     = _INTL("亲密度达标,使用")
    names[Trade]             = _INTL("连接交换")
    names[TradeMale]         = _INTL("雄性连接交换")
    names[TradeFemale]       = _INTL("雌性连接交换")
    names[TradeDay]          = _INTL("白天,连接交换")
    names[TradeNight]        = _INTL("黑夜,连接交换")
    names[TradeItem]         = _INTL("连接交换,携带")
    names[TradeSpecies]      = _INTL("与指定宝可梦连接交换")
    names[CriticalHits]      = _INTL("一局战斗内命中要害次数")
    names[DamageDone]        = _INTL("战斗后损失HP")
    names[SweetItem]         = _INTL("携带糖饰转圈")
    names[CollectItems]      = _INTL("收集999个")
    return nil if names.length <= method
    return names[method]
  end
  
end