package pokemon.runtime.battle;

import pokemon.runtime.pokemon.PbsData;

/**
 * Stage 4 / M0: {@code class PBTypes} (PBTypes_Extra.rb:11-91) plus the three
 * class-level members the Compiler generates onto the same class
 * ({@code Compiler_PBS:442-454}: one constant per type, {@code self.getName},
 * {@code self.getCount}, {@code self.maxValue}) and the effectiveness chart it
 * builds ({@code Compiler_PBS:426-440}, saved as {@code Data/types.dat}).
 *
 * <h2>Where the data comes from</h2>
 * The plugin's {@code @@TypeData = load_data("Data/types.dat")}
 * (PBTypes_Extra.rb:14-23) is {@code [pseudotypes, specialtypes, typechart]}
 * (Compiler_PBS:453). This runtime has no ambient {@code $PokemonTemp} /
 * {@code Data/*.dat} accessor: the PBS tables live in one {@link PbsData}
 * instance that the caller passes in, matching the runtime's existing
 * convention ({@code WildGenerator.natureOf(PbsData,Pokemon)},
 * {@code PokemonStats.experienceForLevel(String,int)}). Signatures were fixed
 * by the Lead for M0.
 *
 * <h2>Documented deviations</h2>
 * <ul>
 * <li><b>Type identity is the internal-name String</b> ({@code "FIRE"},
 *     {@code "QMARKS"}), not the numeric id: {@code BattleMove.type()} is a
 *     String ({@code BattleMove.java:26-28}) and the runtime passes type names
 *     everywhere. The id-based {@code targetType<0} test of
 *     PBTypes_Extra.rb:43 has no name-space equivalent; {@code null} already
 *     means "no type" there (Ruby {@code !targetType}).</li>
 * <li><b>{@code getEffectiveness} is computed from the per-type lists instead
 *     of indexing the precomputed {@code typechart}</b>. The two are the same
 *     function: Compiler_PBS:428-437 builds {@code typechart[j*count+i]} purely
 *     from {@code typehash[i]}'s Weaknesses/Resistances/Immunities containing
 *     {@code typehash[j].internalName}, starting every cell at
 *     {@code NORMAL_EFFECTIVE_ONE=2} and overwriting weakness then resistance
 *     then immunity. {@link PbsData.TypeInfo} carries exactly those three
 *     lists, so the cell value is reconstructed value-for-value.</li>
 * <li><b>Pseudo types</b> = {@code TypeInfo.pseudoType} or "type not in the
 *     table": the compiler also pushes every id missing from types.txt into the
 *     pseudo list (Compiler_PBS:420-422), which a per-type boolean cannot
 *     express. In this project types.txt is {@code [0]..[22]} with no gap, so
 *     only the flag branch fires today.</li>
 * <li><b>{@code maxValue} is the highest type id</b>, not the number of types
 *     (Compiler_PBS:389-390, {@code maxValue = [maxValue,type[0]].max}).</li>
 * </ul>
 *
 * <h2>The two scales</h2>
 * {@code getEffectiveness} answers per <em>one</em> target type and returns
 * 0/1/2/4 ({@link PBTypeEffectiveness}). {@code getCombinedEffectiveness}
 * returns the product over up to three types, so a single-typed target is
 * 2*2*2 = {@link PBTypeEffectiveness#NORMAL_EFFECTIVE} = 8. That 8-scale number
 * is what the plugin stores in {@code damageState.typeMod}
 * ({@code Move_Usage_Calculations:73-95} builds {@code [2,2,2]} and multiplies),
 * which is why the single-argument predicates below take an {@code int}
 * {@code typeMod} and the type-name overloads take a {@link PbsData} first.
 */
public final class PBTypes {

    private PBTypes() {
    }

    /**
     * {@code self.maxValue} generated by Compiler_PBS:389-390, 450: the highest
     * type id in types.txt (not the type count). An empty table yields 0, the
     * plugin's initial value.
     */
    public static int maxValue(PbsData pbs) {
        int maxValue = 0;                                                  // Compiler_PBS:389
        if (pbs == null) {
            return maxValue;
        }
        for (PbsData.TypeInfo type : pbs.types.values()) {                 // Compiler_PBS:390
            if (type != null && type.id > maxValue) {
                maxValue = type.id;
            }
        }
        return maxValue;
    }

    /**
     * {@code PBTypes.regularTypesCount} (PBTypes_Extra.rb:25-32): the number of
     * ids in {@code 0..maxValue} that are neither pseudo nor the {@code SHADOW}
     * constant.
     *
     * <p>{@code isConst?(i,PBTypes,:SHADOW)} is true when the generated
     * {@code PBTypes} class has a {@code SHADOW} constant equal to {@code i}
     * (Compiler_PBS:443-445 emits one constant per types.txt entry), i.e. when
     * types.txt defines a type with the internal name {@code SHADOW}. This
     * project does not (PBS/types.txt has {@code [0]..[22]}, no SHADOW), so the
     * comparison never fires here; it is kept because the plugin's loop has
     * it.</p>
     */
    public static int regularTypesCount(PbsData pbs) {
        int maxValue = maxValue(pbs);                                      // PBTypes_Extra.rb:27
        int ret = 0;                                                       // PBTypes_Extra.rb:26
        for (int i = 0; i <= maxValue; i++) {
            PbsData.TypeInfo info = typeById(pbs, i);
            // :28 next if PBTypes.isPseudoType?(i) || isConst?(i,PBTypes,:SHADOW)
            boolean pseudo = info == null || info.pseudoType;              // Compiler_PBS:397 + :420-422
            boolean shadow = info != null && "SHADOW".equals(info.internalName);   // Compiler_PBS:443-445
            if (pseudo || shadow) {
                continue;
            }
            ret += 1;                                                      // PBTypes_Extra.rb:29
        }
        return ret;                                                        // PBTypes_Extra.rb:31
    }

    /**
     * {@code PBTypes.isPseudoType?} (PBTypes_Extra.rb:34-36):
     * {@code loadTypeData[0].include?(type)}. The list holds the types flagged
     * {@code IsPseudoType} (Compiler_PBS:397) plus every id missing from
     * types.txt (:420-422) - the latter is the "type not in PbsData.types"
     * branch.
     */
    public static boolean isPseudoType(PbsData pbs, String type) {
        PbsData.TypeInfo info = pbs == null || type == null ? null : pbs.types.get(type);
        return info == null || info.pseudoType;                            // PBTypes_Extra.rb:35
    }

    /**
     * {@code PBTypes.isSpecialType?} (PBTypes_Extra.rb:38-40):
     * {@code loadTypeData[1].include?(type)}, the types flagged
     * {@code IsSpecialType} (Compiler_PBS:424). A type absent from the list -
     * including an unknown name - is not special.
     */
    public static boolean isSpecialType(PbsData pbs, String type) {
        PbsData.TypeInfo info = pbs == null || type == null ? null : pbs.types.get(type);
        return info != null && info.specialType;                           // PBTypes_Extra.rb:39
    }

    /**
     * {@code PBTypes.getName} (generated by Compiler_PBS:446-448:
     * {@code id=getID(PBTypes,id); return pbGetMessage(MessageTypes::Types,id)}).
     *
     * <p>Three plugin details are reproduced:</p>
     * <ul>
     * <li>{@code getID} (PSystem_Utilities:224-233) returns <b>nil</b> for a
     *     nil/empty argument (:225), so both yield the empty message - and
     *     {@code MessageTypes.get} never returns nil, it returns {@code ""}
     *     (Intl_Messages:555-561, :673-679). Hence {@code ""} and never
     *     null.</li>
     * <li>For a type <b>not</b> known by the module, {@code getID} returns
     *     <b>0</b> (:226-231 {@code return 0}), so an unknown name resolves to
     *     the type with id 0 - the plugin's own quirk, kept here rather than
     *     inventing a null.</li>
     * <li>The display string comes from the types message table
     *     ({@code MessageTypes::Types}, filled by Compiler_PBS:441), which is
     *     {@link PbsData.TypeInfo#name} in this runtime.</li>
     * </ul>
     */
    public static String getName(PbsData pbs, String type) {
        if (pbs == null || type == null || type.isEmpty()) {               // PSystem_Utilities:225 -> nil
            return "";                                                     // Intl_Messages:557
        }
        PbsData.TypeInfo info = pbs.types.get(type);
        if (info == null) {
            info = typeById(pbs, 0);                                       // PSystem_Utilities:230 -> 0
        }
        return info == null || info.name == null ? "" : info.name;         // Compiler_PBS:448
    }

    /**
     * {@code PBTypes.getEffectiveness(attackType,targetType)}
     * (PBTypes_Extra.rb:42-45) = one {@code typechart} cell
     * (Compiler_PBS:428-437): {@code NORMAL_EFFECTIVE_ONE} by default,
     * {@code SUPER_EFFECTIVE_ONE} on a weakness, {@code NOT_EFFECTIVE_ONE} on a
     * resistance and {@code INEFFECTIVE} on an immunity (checked in that order,
     * so an immunity wins over a weakness or resistance - the plugin's
     * {@code type[5]}/{@code type[6]}/{@code type[7]} writes overwrite each
     * other in the same order).
     *
     * <p>{@code targetType == null} is Ruby's {@code !targetType} and returns
     * {@code NORMAL_EFFECTIVE_ONE} (:43). A target or attack type that is not in
     * the table is Ruby's {@code type} / {@code atype} being nil, which leaves
     * the cell at {@code NORMAL_EFFECTIVE_ONE} (Compiler_PBS:433).</p>
     */
    public static int getEffectiveness(PbsData pbs, String attackType, String targetType) {
        if (targetType == null) {                                          // PBTypes_Extra.rb:43
            return PBTypeEffectiveness.NORMAL_EFFECTIVE_ONE;
        }
        PbsData.TypeInfo target = pbs == null ? null : pbs.types.get(targetType);
        PbsData.TypeInfo attack = pbs == null || attackType == null ? null : pbs.types.get(attackType);
        if (target == null || attack == null) {                            // Compiler_PBS:433 `if type && atype`
            return PBTypeEffectiveness.NORMAL_EFFECTIVE_ONE;
        }
        int mod = PBTypeEffectiveness.NORMAL_EFFECTIVE_ONE;                // Compiler_PBS:431
        if (target.weaknesses.contains(attackType, false)) {               // Compiler_PBS:434
            mod = PBTypeEffectiveness.SUPER_EFFECTIVE_ONE;
        }
        if (target.resistances.contains(attackType, false)) {              // Compiler_PBS:435
            mod = PBTypeEffectiveness.NOT_EFFECTIVE_ONE;
        }
        if (target.immunities.contains(attackType, false)) {               // Compiler_PBS:436
            mod = PBTypeEffectiveness.INEFFECTIVE;
        }
        return mod;                                                        // PBTypes_Extra.rb:44
    }

    /**
     * {@code PBTypes.getCombinedEffectiveness}
     * (PBTypes_Extra.rb:47-59): {@code mod1*mod2*mod3}, where a missing or
     * duplicated target type contributes the neutral factor
     * {@code NORMAL_EFFECTIVE_ONE} (:49-50, :51, :54-55).
     *
     * <p>{@code targetType2}/{@code targetType3} may be {@code null} (Ruby
     * {@code nil}). Ruby's extra {@code targetTypeN>=0} guard is the id-space
     * spelling of "a real type"; here an unknown name already contributes 2
     * through {@link #getEffectiveness}, so the guard is not observable and is
     * dropped.</p>
     */
    public static int getCombinedEffectiveness(PbsData pbs, String attackType,
            String targetType1, String targetType2, String targetType3) {
        int mod1 = getEffectiveness(pbs, attackType, targetType1);         // PBTypes_Extra.rb:48
        int mod2 = PBTypeEffectiveness.NORMAL_EFFECTIVE_ONE;               // PBTypes_Extra.rb:49
        int mod3 = PBTypeEffectiveness.NORMAL_EFFECTIVE_ONE;               // PBTypes_Extra.rb:50
        if (targetType2 != null && !targetType2.equals(targetType1)) {     // PBTypes_Extra.rb:51
            mod2 = getEffectiveness(pbs, attackType, targetType2);         // PBTypes_Extra.rb:52
        }
        if (targetType3 != null && !targetType3.equals(targetType1)        // PBTypes_Extra.rb:54-55
                && !targetType3.equals(targetType2)) {
            mod3 = getEffectiveness(pbs, attackType, targetType3);         // PBTypes_Extra.rb:56
        }
        return mod1 * mod2 * mod3;                                         // PBTypes_Extra.rb:58
    }

    // ------------------------------------------------------------------
    // PBTypes_Extra.rb:61-89, one-argument branch: `!targetType1`
    // The value is damageState.typeMod, i.e. the getCombinedEffectiveness
    // result on the NORMAL_EFFECTIVE=8 scale (Move_Usage_Calculations:73-95).
    // ------------------------------------------------------------------

    /** {@code PBTypes.ineffective?(attackType)} (PBTypes_Extra.rb:61-63). */
    public static boolean ineffective(int typeMod) {
        return typeMod == PBTypeEffectiveness.INEFFECTIVE;                 // PBTypes_Extra.rb:62
    }

    /** {@code PBTypes.notVeryEffective?(attackType)} (PBTypes_Extra.rb:67-69). */
    public static boolean notVeryEffective(int typeMod) {
        return typeMod > PBTypeEffectiveness.INEFFECTIVE                   // PBTypes_Extra.rb:68
                && typeMod < PBTypeEffectiveness.NORMAL_EFFECTIVE;
    }

    /** {@code PBTypes.resistant?(attackType)} (PBTypes_Extra.rb:73-75). */
    public static boolean resistant(int typeMod) {
        return typeMod < PBTypeEffectiveness.NORMAL_EFFECTIVE;             // PBTypes_Extra.rb:74
    }

    /** {@code PBTypes.normalEffective?(attackType)} (PBTypes_Extra.rb:79-81). */
    public static boolean normalEffective(int typeMod) {
        return typeMod == PBTypeEffectiveness.NORMAL_EFFECTIVE;            // PBTypes_Extra.rb:80
    }

    /** {@code PBTypes.superEffective?(attackType)} (PBTypes_Extra.rb:85-87). */
    public static boolean superEffective(int typeMod) {
        return typeMod > PBTypeEffectiveness.NORMAL_EFFECTIVE;             // PBTypes_Extra.rb:86
    }

    // ------------------------------------------------------------------
    // PBTypes_Extra.rb:61-89, else branch: `e = getCombinedEffectiveness(...)`
    // `attackType` is a type internal name here (Battler_UseMove_Targeting:177,
    // Move_Usage_Calculations:67-68, AI_Move:42-43, AI_Switch:32).
    // ------------------------------------------------------------------

    /** {@code PBTypes.ineffective?(attackType,t1,t2,t3)} (PBTypes_Extra.rb:61-65). */
    public static boolean ineffective(PbsData pbs, String attackType,
            String targetType1, String targetType2, String targetType3) {
        int e = getCombinedEffectiveness(pbs, attackType, targetType1, targetType2, targetType3);   // :63
        return e == PBTypeEffectiveness.INEFFECTIVE;                       // PBTypes_Extra.rb:64
    }

    /** {@code PBTypes.notVeryEffective?(attackType,t1,t2,t3)} (PBTypes_Extra.rb:67-71). */
    public static boolean notVeryEffective(PbsData pbs, String attackType,
            String targetType1, String targetType2, String targetType3) {
        int e = getCombinedEffectiveness(pbs, attackType, targetType1, targetType2, targetType3);   // :69
        return e > PBTypeEffectiveness.INEFFECTIVE                         // PBTypes_Extra.rb:70
                && e < PBTypeEffectiveness.NORMAL_EFFECTIVE;
    }

    /** {@code PBTypes.resistant?(attackType,t1,t2,t3)} (PBTypes_Extra.rb:73-77). */
    public static boolean resistant(PbsData pbs, String attackType,
            String targetType1, String targetType2, String targetType3) {
        int e = getCombinedEffectiveness(pbs, attackType, targetType1, targetType2, targetType3);   // :75
        return e < PBTypeEffectiveness.NORMAL_EFFECTIVE;                   // PBTypes_Extra.rb:76
    }

    /** {@code PBTypes.normalEffective?(attackType,t1,t2,t3)} (PBTypes_Extra.rb:79-83). */
    public static boolean normalEffective(PbsData pbs, String attackType,
            String targetType1, String targetType2, String targetType3) {
        int e = getCombinedEffectiveness(pbs, attackType, targetType1, targetType2, targetType3);   // :81
        return e == PBTypeEffectiveness.NORMAL_EFFECTIVE;                  // PBTypes_Extra.rb:82
    }

    /** {@code PBTypes.superEffective?(attackType,t1,t2,t3)} (PBTypes_Extra.rb:85-89). */
    public static boolean superEffective(PbsData pbs, String attackType,
            String targetType1, String targetType2, String targetType3) {
        int e = getCombinedEffectiveness(pbs, attackType, targetType1, targetType2, targetType3);   // :87
        return e > PBTypeEffectiveness.NORMAL_EFFECTIVE;                   // PBTypes_Extra.rb:88
    }

    /**
     * The type whose id is {@code id}, or null for a gap in the numbering. The
     * plugin never needs this: it addresses {@code typehash[i]} and
     * {@code typechart[j*count+i]} directly by id (Compiler_PBS:428-440). Only
     * {@link #regularTypesCount}'s {@code for i in 0..maxValue} loop needs it.
     */
    private static PbsData.TypeInfo typeById(PbsData pbs, int id) {
        if (pbs == null) {
            return null;
        }
        for (PbsData.TypeInfo type : pbs.types.values()) {
            if (type != null && type.id == id) {
                return type;
            }
        }
        return null;
    }
}
